const questions = [
"Wat is je favoriete herinnering uit je kindertijd?",
"Als je een superkracht kon hebben, welke zou dat zijn?",
"Wat is het gekste dat je ooit hebt gedaan?",
"Waar zou je willen wonen als alles mogelijk was?",
"Wat is je favoriete vakantieherinnering?",
"Welke drie dingen zou je meenemen naar een onbewoond eiland?",
"Als je elke taal ter wereld kon spreken, welke taal zou je als eerste willen leren?",
"Wat is je favoriete film en waarom?",
"Welk beroep zou je kiezen als geld geen rol speelde?",
"Wat is je grootste angst?",
"Als je een dier kon zijn, welk dier zou je dan kiezen?",
"Wat is je favoriete muziekgenre?",
"Wie is je grootste voorbeeld in het leven?",
"Wat is het beste advies dat je ooit hebt gekregen?",
"Wat zou je doen met een miljoen euro?",
"Welke historische figuur zou je willen ontmoeten?",
"Wat is je favoriete seizoen en waarom?",
"Wat is het mooiste boek dat je ooit hebt gelezen?",
"Wat vind je het leukst aan jezelf?",
"Als je je naam zou kunnen veranderen, wat zou het dan worden?",
"Wat is je droomvakantie?",
"Welke uitvinding zou je doen als alles mogelijk was?",
"Wat is het beste cadeau dat je ooit hebt gekregen?",
"Wat is je grootste prestatie tot nu toe?",
"Wat is het grappigste dat je recent hebt meegemaakt?",
"Wat zou je doen als je onzichtbaar was voor een dag?",
"Wat is je favoriete maaltijd?",
"Wat is je grootste irritatie?",
"Wat doe je om te ontspannen?",
"Wat zou je doen als je de loterij won?",
"Wie is je favoriete fictieve personage?",
"Wat is je favoriete sport?",
"Wat is het laatste boek dat je hebt gelezen?",
"Wat zou je graag willen leren?",
"Wat is je favoriete feestdag?",
"Wat is je favoriete familietraditie?",
"Wat is je favoriete plek om te zijn?",
"Wat is het meest avontuurlijke dat je ooit hebt gedaan?",
"Wat is het mooiste cadeau dat je ooit hebt gegeven?",
"Wat zou je doen als je een dag kon ruilen met iemand anders?",
"Wat is je favoriete drankje?",
"Wat is het belangrijkste in een vriendschap?",
"Welke taal zou je willen spreken?",
"Wat is je favoriete tv-programma?",
"Wat is je grootste droom?",
"Wat is je favoriete manier om je weekend door te brengen?",
"Wat is je favoriete dier?",
"Wat zou je doen als je voor één dag de baas was van het land?",
"Wat is je favoriete herinnering met vrienden?",
"Wat is je grootste wens voor de toekomst?",
"Wat zou je doen als je geen verplichtingen had?",
"Wat is je favoriete snack?",
"Wat is het leukste dat je ooit hebt gedaan met je familie?",
"Wat zou je willen veranderen aan de wereld?",
"Wat is je favoriete bloem?",
"Wat is je grootste passie?",
"Wat is je favoriete muzieknummer?",
"Wat is je favoriete herinnering uit je schooltijd?",
"Wat is je favoriete hobby?",
"Wat is het engste dat je ooit hebt meegemaakt?",
"Wat is je favoriete sportteam?",
"Wat is je favoriete kleur?",
"Wat is het beste dat je ooit hebt bereikt?",
"Wat is je favoriete geur?",
"Wat is je favoriete plek in huis?",
"Wat is je favoriete ochtendritueel?",
"Wat zou je doen als je de toekomst kon zien?",
"Wat is je favoriete herinnering aan je grootouders?",
"Wat is je favoriete tijd van de dag?",
"Wat is je favoriete bordspel?",
"Wat is je favoriete restaurant?",
"Wat zou je doen als je een dag geen technologie had?",
"Wat is je favoriete dessert?",
"Wat zou je doen als je terug in de tijd kon gaan?",
"Wat is je favoriete herinnering van de afgelopen 5 jaar?",
"Wat zou je doen als je de kans had om iets nieuws te beginnen?",
"Wat is je favoriete manier om te ontspannen?",
"Wat is je favoriete parfum of aftershave?",
"Wat zou je doen als je een week vrij had en niets hoefde te doen?",
"Wat is je favoriete app op je telefoon?",
"Wat is je favoriete herinnering met je partner?",
"Wat is je favoriete ijsje?",
"Wat zou je doen als je voor een dag beroemd was?",
"Wat is je favoriete ochtendroutine?",
"Wat zou je doen als je voor één dag alles kon leren wat je wilde?",
"Wat is je favoriete bezigheid op een regenachtige dag?",
"Wat zou je doen als je onbeperkt geld had voor één dag?",
"Wat is je favoriete gerecht om te koken?",
"Wat is je favoriete herinnering aan een feest?",
"Wat zou je doen als je een jaar vrij had?",
"Wat is je favoriete feestdag?",
"Wat zou je doen als je een geheim kon ontdekken?",
"Wat is je favoriete manier om tijd door te brengen met vrienden?",
"Wat is je favoriete herinnering uit je jeugd?",
"Wat zou je doen als je voor een dag een dier kon zijn?",
"Wat is je favoriete liedje van vroeger?",
"Wat zou je doen als je je droomhuis kon bouwen?",
"Wat is je favoriete activiteit in de zomer?",
"Wat is je favoriete kledingstuk?",
"Wat zou je doen als je morgen geen verplichtingen had?"
]
